# Generated by Django 2.0.2 on 2018-03-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان')),
                ('session_datetime', models.DateTimeField(verbose_name='تاریخ برگزاری')),
                ('start_session_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_session_time', models.TimeField(verbose_name='ساعت پایان')),
                ('presentations_count', models.IntegerField(verbose_name='تعداد ارائه\u200cها')),
                ('address', models.CharField(max_length=255, verbose_name='نشانی محل برگزاری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
