# Generated by Django 2.0.2 on 2018-03-24 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('presentation_type', models.CharField(choices=[('speech', 'Speech'), ('workshop', 'Workshop'), ('poster', 'Poster'), ('free_discussion', 'Free discussion')], max_length=30, verbose_name='نوع ارائه')),
                ('equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='تجهیزات مورد نیاز')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=10, verbose_name='شمارهٔ تلفن همراه')),
                ('article_attachment', models.FileField(blank=True, null=True, upload_to='media/article', verbose_name='فایل مقاله')),
                ('slides_attachment', models.FileField(blank=True, null=True, upload_to='media//slides/', verbose_name='فایل اسلایدها')),
                ('duration', models.IntegerField(verbose_name='مدت زمان مورد نیاز به دقیقه')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Session', verbose_name='جلسه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
