# Generated by Django 2.0.2 on 2018-03-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20180324_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='آیا تاییدشده است؟'),
        ),
    ]
