# Generated by Django 2.0.2 on 2018-04-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_presentation_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
