# Generated by Django 2.0.2 on 2018-04-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_auto_20180402_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.CharField(max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='equipment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='تجهیزات مورد نیاز'),
        ),
    ]
