# Generated by Django 2.0.2 on 2018-04-02 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0006_auto_20180402_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('creation_datetime', models.DateTimeField(verbose_name='تاریخ ثبت نظر')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Presentation', verbose_name='ارائه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='SessionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('creation_datetime', models.DateTimeField(verbose_name='تاریخ ثبت نظر')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Session', verbose_name='جلسه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
